name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

        # ensure astro build works
      - name: Run astro build
        run: npm run build:astro
